config/routes.rb
Rails.application.routes.draw do
  post 'api/news'
  get 'api/:date_1/:date_2', to: 'api#news_between'
  get 'api/create_news', to:'api#create_news'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  post 'retweeets/:tweet_id', to: 'retweets#create', as: 'retweets'
  post 'likes/:tweet_id', to: 'likes#create', as: 'likes'

  devise_for :users, controllers: {
          sessions: 'users/sessions'
        }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tweets do
    collection do
      get :search_tweet
    end
  end

  get '/tweets/hashtag/:name', to: 'tweets#hashtags'
  root 'tweets#index'
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :tags
  validates :content, presence: true
  has_many :likes, dependent: :destroy
  has_many :retweets, dependent: :destroy
  attribute :total_likes, :integer, default: 0
  attribute :total_retweet, :integer, default: 0

  paginates_per 50

  after_create do
    tweet = Tweet.find_by(id: self.id)
    hashtag = self.content.scan(/#\w+/)
    hashtag.uniq.map do |h|
      tag = Tag.find_or_create_by(name: h.downcase.delete('#'))
      tweet.tags << tag
    end
  end

  scope :tweets_for_me, -> (user_ids) { where(user_id: user_ids)}
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, except: :index
  def index
    @q = Tweet.ransack(params[:q])
    if user_signed_in?
      @followers = current_user.followings.pluck(:followed_id)
      @tweet = Tweet.new
      @tweets = Tweet.tweets_for_me(@followers).order(:created_at).page params[:page]
    else
      @tweets = Tweet.order(:created_at).page params[:page]
    end
  end

  def search_tweet
    @q = Tweet.ransack(params[:q])
    @tweets_search = @q.result(distinct: true)
  end

  def hashtag
    @tag = Tag.find_by(name: params[:name])
    @tweets = @tag.tweets

  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user = current_user
    if @tweet.save
      flash[:notice] = 'Tweet creado exitosamente'
      redirect_to tweets_path
    else
      render :new
    end
  end

  def show
    @tweet = Tweet.find(params[:id])
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
  def tweet_params
    params.require(:tweet).permit(:content, :image_url)
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
  def render_hashtag(body)
    body.gsub(/#\w+/) {|w| link_to w, "tweets/hashtag/#{w.delete('#')}"}.html_safe
  end
end

app/views/tweets/_form.html.erb
<h3>Crea tu tweet</h3>
<%= form_with(model: @tweet, local: true) do |form| %>
<% if @tweet.errors.any? %>
  <div class="alert alert-danger" id="error-explanation">
    <h2><%= pluralize(@tweet.errors.count, "error") %> Prohibited this tweet from being saved</h2>
    <ul>
      <% @tweet.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

    <div class="form-group">
      <%= form.label :content, "Mensaje" %>
      <%= form.text_area :content, class: "form-control" %>
    </div>

    <div class="form-group">
    <%= form.label :image_url, "URL Imagen" %>
    <%= form.text_field :image_url, class: "form-control" %>
    </div>

    <div class="my-3">
      <%= form.submit "Create", class:"btn btn-primary" %>
    </div>
<% end %>

app/views/tweets/create.html.erb
<h1>Tweets#create</h1>
<p>Find me in app/views/tweets/create.html.erb</p>

app/views/tweets/destroy.html.erb
<h1>Tweets#destroy</h1>
<p>Find me in app/views/tweets/destroy.html.erb</p>

app/views/tweets/edit.html.erb
<h1>Tweets#edit</h1>
<p>Find me in app/views/tweets/edit.html.erb</p>

app/views/tweets/hashtags.html.erb
 Por definir vista

app/views/tweets/index.html.erb
<h1>Tweets#index</h1>
<p>Find me in app/views/tweets/index.html.erb</p>
  <%= search_form_for @q, url: search_tweet_tweets_path do |f| %>
    <%# # Search if the name field contains... %>
    <%= f.label :content_cont %>
    <%= f.search_field :content_cont %>
    <%= f.submit %>
  <% end %>


<% if current_user %>
  <%= render "form" %>

  <% @tweets.each do |tweet| %>
    <div class="card my-3">
      <div class="row">
        <div class="col">
          <%= image_tag "#{User.find_by(id: tweet.user_id).image_url}", class: "max-width: 5px" %>
          <%= render_hashtag(tweet.content) %>
        </div>
        <div class="col">
          <p><%= User.find_by(id: tweet.user_id).username %></p>
        </div>
      </div>
      <%= image_tag "#{tweet.image_url}", class: "card-img-top" %>
      <div class="card-body">
        <p class="card-text"><%= tweet.content %></p>
      </div>

      <div class="row">
        <div class="col">
          <%= link_to "Like - Total:#{tweet.total_likes}", likes_path(tweet.id), method: :post, class:"btn btn-primary" %>
        </div>
        <div class="col">
          <%= link_to "Retweet- Total: #{tweet.total_retweet}", retweets_path(tweet.id), method: :post, class:"btn btn-secondary" %>
        </div>
        <div class="col-8 text-right">
          <%= link_to distance_of_time_in_words(Time.now, tweet.created_at), tweet_path(tweet.id), class: "btn btn-info" %>
        </div>
      </div>

    </div>
  <% end %>

<% else %>
  <% @tweets.each do |tweet| %>
  <div class="card my-3">
    <div class="row">
      <div class="col">
        <%= image_tag "#{User.find_by(id: tweet.user_id).image_url}", class: "max-width: 5px" %>
      </div>
      <div class="col">
        <p><%= User.find_by(id: tweet.user_id).username %></p>
      </div>
    </div>
    <%= image_tag "#{tweet.image_url}", class: "card-img-top" %>
    <div class="card-body">
      <p class="card-text"><%= tweet.content %></p>
    </div>

    <%= link_to distance_of_time_in_words(Time.now, tweet.created_at), tweet_path(tweet.id), class: "btn btn-info text-right" %>

    </div>

  <% end %>
<% end %>


<%= paginate @tweets %>

app/views/tweets/new.html.erb
<h1>Nuevo Tweet</h1>

<%= render "form" %>

<%= link_to "Atrás", tweets_path, class:"btn btn-secondary" %>

app/views/tweets/search_tweet.html.erb
<% @tweets_search.each do |tweet| %>
  <div class="card my-3">
    <div class="row">
      <div class="col">
        <%= image_tag "#{User.find_by(id: tweet.user_id).image_url}", class: "max-width: 5px" %>
      </div>
      <div class="col">
        <p><%= User.find_by(id: tweet.user_id).username %></p>
      </div>
    </div>
    <%= image_tag "#{tweet.image_url}", class: "card-img-top" %>
    <div class="card-body">
      <p class="card-text"><%= tweet.content %></p>
    </div>

    <div class="row">
      <div class="col">
        <%= link_to "Like - Total:#{tweet.total_likes}", likes_path(tweet.id), method: :post, class:"btn btn-primary" %>
      </div>
      <div class="col">
        <%= link_to "Retweet- Total: #{tweet.total_retweet}", retweets_path(tweet.id), method: :post, class:"btn btn-secondary" %>
      </div>
      <div class="col-8 text-right">
        <%= link_to distance_of_time_in_words(Time.now, tweet.created_at), tweet_path(tweet.id), class: "btn btn-info" %>
      </div>
    </div>
  </div>
<% end %>

app/views/tweets/show.html.erb
<h1>Tweets#show</h1>
<p>Find me in app/views/tweets/show.html.erb</p>

<div class="card my-3">
  <div class="row">
    <div class="col">
      <%= image_tag "#{User.find_by(id: @tweet.user_id).image_url}", class: "max-width: 5px" %>
    </div>
    <div class="col">
      <p><%= User.find_by(id: @tweet.user_id).username %></p>
    </div>
  </div>
  <%= image_tag @tweet.image_url, class: "card-img-top" %>
  <div class="card-body">
    <p class="card-text"><%= @tweet.content %></p>
  </div>

</div>

app/views/tweets/update.html.erb
<h1>Tweets#update</h1>
<p>Find me in app/views/tweets/update.html.erb</p>