config/routes.rb
Rails.application.routes.draw do
  post 'api/news'
  get 'api/:date_1/:date_2', to: 'api#news_between'
  get 'api/create_news', to:'api#create_news'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  post 'retweeets/:tweet_id', to: 'retweets#create', as: 'retweets'
  post 'likes/:tweet_id', to: 'likes#create', as: 'likes'

  devise_for :users, controllers: {
          sessions: 'users/sessions'
        }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tweets do
    collection do
      get :search_tweet
    end
  end

  get '/tweets/hashtag/:name', to: 'tweets#hashtags'
  root 'tweets#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :tweet

  def add_like
    tweet.update(total_likes: tweet.total_likes += 1)
  end

  def delete_like
    tweet.update(total_likes: tweet.total_likes -= 1)
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/retweet.rb
class Retweet < ApplicationRecord
  belongs_to :user
  belongs_to :tweet

  def add_retweet
    tweet.update(total_retweet: tweet.total_retweet += 1)
  end

  def delete_retweet
    tweet.update(total_retweet: tweet.total_retweet -= 1)
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :tweets
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :tags
  validates :content, presence: true
  has_many :likes, dependent: :destroy
  has_many :retweets, dependent: :destroy
  attribute :total_likes, :integer, default: 0
  attribute :total_retweet, :integer, default: 0

  paginates_per 50

  after_create do
    tweet = Tweet.find_by(id: self.id)
    hashtag = self.content.scan(/#\w+/)
    hashtag.uniq.map do |h|
      tag = Tag.find_or_create_by(name: h.downcase.delete('#'))
      tweet.tags << tag
    end
  end

  scope :tweets_for_me, -> (user_ids) { where(user_id: user_ids)}
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_token_authenticatable

  has_many :tweets, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :retweets, dependent: :destroy

  attribute :image_url, :string, default: 'https://secure.gravatar.com/avatar/8d2ab8f62e9bf17a95aab0dd1c83811e?s=96&d=mm&r=g'
  # Active
  has_many :active_relationships, class_name:  "Relationship",
            foreign_key: "follower_id", dependent: :destroy
  # Passive
  has_many :passive_relationships, class_name:  "Relationship",
            foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/api_controller.rb
class ApiController < ActionController::API
  # include ActionController::HttpAuthentication::Basic::ControllerMethods
  # http_basic_authenticate_with email: user.email, password: user.password
  acts_as_token_authentication_handler_for User

  def news
    @tweets = Tweet.all.order(id: :desc).limit(50)
    @tweets.map do |tweet|
      {
        id: tweet.id,
        content: tweet.content,
        user_id: tweet.user_id,
        retweets_count: tweet.retweets.count,
        retweeted_from: tweet.retweets.map { |retweet| {user_email: retweet.user.email} }
      }
    end
    render json: @tweets
  end

  def news_between
    selected_date_1 = Date.parse(params[:date_1])
    selected_date_2 = Date.parse(params[:date_2])
    # This will look for records on the given date between 00:00:00 and 23:59:59
    @tweets = Tweet.where(
       created_at: selected_date_1..selected_date_2)

       render json: @tweets
  end

  def create_news
    @tweet = Tweet.create(
      content: params.require(:content),
      user: current_user
    )

    render json: @tweet
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    # Permit the `subscribe_newsletter` parameter along with the other
    # sign up parameters.
    devise_parameter_sanitizer.permit(:sign_up, keys: [:image_url, :username])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    @like = Like.find_by(user_id: current_user.id, tweet_id: params[:tweet_id])
    if @like && @like.active
      @like.update_attributes(active: false)
      @like.delete_like
    elsif @like && !@like.active
      @like.update_attributes(active: true)
      @like.add_like
    else
      @like = Like.create(user_id: current_user.id, tweet_id: params[:tweet_id])
      @like.add_like
    end
    redirect_to root_path
  end
end

app/controllers/retweets_controller.rb
class RetweetsController < ApplicationController
  before_action :authenticate_user!

  def create
    @retweet = Retweet.find_by(user_id: current_user.id, tweet_id: params[:tweet_id])
    if @retweet && @retweet.active
      @retweet.update_attributes(active: false)
      @retweet.delete_retweet
    elsif @retweet && !@retweet.active
      @retweet.update_attributes(active: true)
      @retweet.add_retweet
    else
      @retweet = Retweet.create(user_id: current_user.id, tweet_id: params[:tweet_id])
      @retweet_u = Tweet.create(user_id: current_user.id)
      @retweet.add_retweet
    end
    redirect_to root_path
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, except: :index
  def index
    @q = Tweet.ransack(params[:q])
    if user_signed_in?
      @followers = current_user.followings.pluck(:followed_id)
      @tweet = Tweet.new
      @tweets = Tweet.tweets_for_me(@followers).order(:created_at).page params[:page]
    else
      @tweets = Tweet.order(:created_at).page params[:page]
    end
  end

  def search_tweet
    @q = Tweet.ransack(params[:q])
    @tweets_search = @q.result(distinct: true)
  end

  def hashtag
    @tag = Tag.find_by(name: params[:name])
    @tweets = @tag.tweets

  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user = current_user
    if @tweet.save
      flash[:notice] = 'Tweet creado exitosamente'
      redirect_to tweets_path
    else
      render :new
    end
  end

  def show
    @tweet = Tweet.find(params[:id])
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
  def tweet_params
    params.require(:tweet).permit(:content, :image_url)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def edit
  end 

  def update
  end

  def destroy
  end

  def show
  end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/retweets_helper.rb
module RetweetsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
  def render_hashtag(body)
    body.gsub(/#\w+/) {|w| link_to w, "tweets/hashtag/#{w.delete('#')}"}.html_safe
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinalProyTwitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <div class="container">


    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>

    <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <%= link_to "Inicio", tweets_path, class: "nav-item nav-link" %>

      <% if current_user %>
        <%= link_to "Crear Tweet", new_tweet_path, class: "nav-item nav-link" %>
        <%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete, class: "nav-item nav-link" %>
      <% else %>
        <%= link_to "Iniciar sesión", new_user_session_path, class: "nav-item nav-link" %>
        <%= link_to "Crear cuenta", new_user_registration_path, class: "nav-item nav-link" %>
      <% end %>

    </div>
  </div>
</nav>